[build]
  publish = "dist"
  command = "npm run build"
[[redirects]]
  from = "http://grammysglutenfreegoodies.netlify.com/*"
  to = "https://grammys.herohtar.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://grammysglutenfreegoodies.netlify.com/*"
  to = "https://grammys.herohtar.com/:splat"
  status = 301
  force = true
